name: Python application test

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Run all tests
        run: pytest
        if: "github.event.inputs.deployment_target == 'all'"
      - name: Run smoke tests
        run: pytest -v -m smoke
        if: "github.event.inputs.deployment_target == 'smoke'"
      - name: Run regression tests
        run: pytest -m regression
